name: iOS 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: "Lint "
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Linting
        run: make clean-ios analyze-ios

  test:
    name: "Test & Report "
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-ios test-ios DEVICE='iPhone 14'

  build:
    name: "Build "
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build
        run: make clean-ios build-ios
