name: Shared 🤝

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cancel-previous:
    name: Cancel Previous
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  lint-android:
    name: "Lint Android 🤖"
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-gradle lint-shared-android

  lint-common:
    name: "Lint Common 🤼"
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-gradle lint-shared-common

  lint-ios:
    name: "Lint iOS "
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-gradle lint-shared-ios

  lint-kotlinter:
    name: "Kotlinter 🧹"
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-gradle lint-shared-kotlinter

  test-android:
    name: "Test Android 🤖"
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-gradle test-shared-android

  test-ios:
    name: "Test iOS "
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test
        run: make clean-gradle test-shared-ios
